title: "Sneksoft Studios"
description: "VR • Games • Tools • Immersive Tech"

url: "https://sneksoft-studios.github.io"

baseurl: "/Sneksoft.github.io"

markdown: kramdown
theme: null

future: true
permalink: /:title/
