title: "Sneksoft Studios"
description: "VR • Games • Tools • Immersive Tech"

# Required for GitHub Pages PROJECT SITES
url: "https://sneksoft-studios.github.io"
baseurl: "/Sneksoft.github.io"

# Enable Jekyll features
markdown: kramdown
theme: minima

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true

# Ensure assets & folders are included
include:
  - assets

sass:
  style: compressed
